import Head from 'next/head'
import {
  Courses,
  Container,
  Title,
  Jumbotron,
  MenuOptions
} from '../components'

export default function Home() {
  return (
    <>
      <Head>
        <title>HIMFG - INICIO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://res.cloudinary.com/diuxbqmn5/image/upload/v1677114497/himfg-logo_ewzx59.webp" />
      </Head>
      <Jumbotron />
      <Container>
        <Title>Direcciones del HIMFG</Title>
        <MenuOptions />
      </Container>
    </>
  )
}
