import { useState, useEffect, useContext } from 'react'
import { useRouter } from 'next/router'
import Head from 'next/head'
import Script from 'next/script'
import { RegisterForm, Container, Title } from '../components'
import { UserContext } from '../contexts'

const Register = ()=>{
    const [course, setIsCourse] = useState(null)
    const router = useRouter()
    const { user }= useContext(UserContext)
    if(user){
        router.push('/ensenanza/offer')
    }
    useEffect(()=>{
        setIsCourse(JSON.parse(localStorage.getItem('course')))
    },[])
    return (
        <>
            <Head>
                <title>Inscripción online</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="https://res.cloudinary.com/diuxbqmn5/image/upload/v1677114497/himfg-logo_ewzx59.webp" />
            </Head>
            <Container>
                {
                    !course ?
                    <Title>Inscripción</Title>
                    :
                    <Title>Inscripción al curso : {course.course_name}</Title>
                }
                <RegisterForm
                    path={!course ? '/userlogin' : '/payment'}
                />
            </Container>
        </>
    )
}
export default Register