export const images = [
    {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/5.webp",
        width: 150,
        height: 200,
        caption: "Los niños pidiendo posada o la peregrinación - Diego Rivera",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/1.webp",
        width: 390,
        height: 200,
        caption: "Los niños pidiendo posada o la peregrinación - Diego Rivera",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/3.webp",
        width: 390,
        height: 195,
        caption: "315H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/43.webp",
        width: 200,
        height: 130,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/12.webp",
        width: 320,
        height: 213,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/9.webp",
        width: 150,
        height: 200,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/17.webp",
        width: 600,
        height: 200,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/18.webp",
        width: 280,
        height: 200,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/14.webp",
        width: 200,
        height: 250,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/19.webp",
        width: 900,
        height: 250,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/4.webp",
        width: 1000,
        height: 148,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/13.webp",
        width: 370,
        height: 250,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/16.webp",
        width: 200,
        height: 250,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/59.webp",
        width: 1100,
        height: 250,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/51.webp",
        width: 400,
        height: 250,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/50.webp",
        width: 400,
        height: 250,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/60.webp",
        width: 500,
        height: 250,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/45.webp",
        width: 300,
        height: 200,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/2.webp",
        width: 1000,
        height: 400,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/52.webp",
        width: 500,
        height: 600,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/44.webp",
        width: 1000,
        height: 600,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/46.webp",
        width: 1000,
        height: 600,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/21.webp",
        width: 450,
        height: 600,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/39.webp",
        width: 1100,
        height: 200,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/11.webp",
        width: 100,
        height: 150,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/62.webp",
        width: 900,
        height: 450,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/61.webp",
        width: 250,
        height: 400,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/58.webp",
        width: 650,
        height: 200,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/24.webp",
        width: 150,
        height: 200,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/27.webp",
        width: 1000,
        height: 148,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/11-1.webp",
        width: 100,
        height: 150,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/30.webp",
        width: 90,
        height: 100,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/39-1.webp",
        width: 1100,
        height: 200,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/56.webp",
        width: 900,
        height: 250,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/53.webp",
        width: 500,
        height: 600,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/22.webp",
        width: 150,
        height: 200,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/54-1.webp",
        width: 500,
        height: 600,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/26.webp",
        width: 280,
        height: 500,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/39-2.webp",
        width: 1100,
        height: 200,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/49.webp",
        width: 1000,
        height: 600,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/10.webp",
        width: 110,
        height: 150,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/54-2.webp",
        width: 520,
        height: 600,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/48.webp",
        width: 1060,
        height: 600,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/57.webp",
        width: 850,
        height: 250,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/15.webp",
        width:550,
        height: 400,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/23.webp",
        width: 130,
        height: 200,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/40.webp",
        width: 1090,
        height: 600,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/42.webp",
        width: 550,
        height: 900,
        caption: "201H (gratisography.com)",
      },
      {
        src: "https://archivos.him.edu.mx/graficos/legado-artistico/47.webp",
        width: 1090,
        height: 600,
        caption: "201H (gratisography.com)",
      },
]