export const images = [
    {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/5.webp",
        width: 150,
        height: 200,
        caption: "Los niños - Fernando Chico Ponce de León",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/1.webp",
        width: 390,
        height: 200,
        caption: "Los niños pidiendo posada o la peregrinación - Diego Rivera",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/3.webp",
        width: 390,
        height: 195,
        caption: "La piñata - Diego Rivera",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/43.webp",
        width: 200,
        height: 130,
        caption: "El sueño de la Malinche, galería de arte mexicano Antonio Ruíz",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/12.webp",
        width: 320,
        height: 213,
        caption: "Niños - Pedro Valencia Mayoral ",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/9.webp",
        width: 150,
        height: 200,
        caption: "Protección que la institución otorga a los niños mexicanos - Ángela Gurría",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/17.webp",
        width: 600,
        height: 200,
        caption: "Afecto (La familia) - Miguel García 'El Marquéz de Jadraque'",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/18.webp",
        width: 280,
        height: 200,
        caption: "Traslación - Carlos Torres",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/14.webp",
        width: 200,
        height: 250,
        caption: "Caminante - Autor no identificado",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/19.webp",
        width: 900,
        height: 250,
        caption: "Este es mi mundo - David Correa",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/4.webp",
        width: 1000,
        height: 148,
        caption: "Nutrición (México rico y capaz de mantener a sus hijos) Francisco Eppens",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/13.webp",
        width: 370,
        height: 250,
        caption: "Sin título Pablo O Higgins",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/16.webp",
        width: 200,
        height: 250,
        caption: "Alegría - Irene Zundel",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/59.webp",
        width: 1100,
        height: 250,
        caption: "El carrusel - David Correa",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/51.webp",
        width: 400,
        height: 250,
        caption: "Parvada - Santiago Soto Urrutia",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/50.webp",
        width: 400,
        height: 250,
        caption: "Xochiquetzal (flor preciosa)  - Santiago Soto Urrutia",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/60.webp",
        width: 500,
        height: 250,
        caption: "Durero - Sebastian",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/45.webp",
        width: 300,
        height: 200,
        caption: "El harca del Nóe - Krytzia Dabdoub de MIvielle y Sofia Minivielle Dabdoub",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/2.webp",
        width: 1000,
        height: 400,
        caption: "Hacia la salud (dedicado a los niños de México) - Fanny Rabel",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/52.webp",
        width: 500,
        height: 600,
        caption: "Hospital Infantil - Partitura de Arturi garcìa Herrera",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/44.webp",
        width: 1000,
        height: 600,
        caption: "Los niños del futuro - Alejandro Reyna",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/46.webp",
        width: 1000,
        height: 600,
        caption: "Lluvia  - Santiago Soto Urrutia",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/21.webp",
        width: 450,
        height: 600,
        caption: "Hospital del niño - Anónimo",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/39.webp",
        width: 1100,
        height: 200,
        caption: "Boceto 1 - Francisco Eppens",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/11.webp",
        width: 100,
        height: 150,
        caption: "Sin título 3 Alejandro Reyna, “M.Aless”",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/62.webp",
        width: 900,
        height: 450,
        caption: "Letras",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/61.webp",
        width: 250,
        height: 400,
        caption: "Ixtlilton Dr Fernando Chico Ponce de Leoón - Dr Jaime Nieto",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/58.webp",
        width: 650,
        height: 200,
        caption: "El circo - David Correa",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/24.webp",
        width: 150,
        height: 200,
        caption: "Dr. Federico Gómez - Fernando Chico Ponce de León",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/27.webp",
        width: 1000,
        height: 148,
        caption: "Desnutrición (la tierra mexicana explotada)  - Francisco Eppens",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/11-1.webp",
        width: 100,
        height: 150,
        caption: "Sin título 2 Alejandro Reyna, “M.Aless”",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/30.webp",
        width: 90,
        height: 100,
        caption: "Sin título - José Luis Cuevas",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/39-1.webp",
        width: 1100,
        height: 200,
        caption: "Boceto 2 - Francisco Eppens",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/56.webp",
        width: 900,
        height: 250,
        caption: "Los juguetes perdidos - Leovigildo Martínez",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/53.webp",
        width: 500,
        height: 600,
        caption: "Himno al Hospital Infaltil de México Letra de Samuel Maynez Champion, Música de Coral Mesina",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/22.webp",
        width: 150,
        height: 200,
        caption: "San francisco de Asis - Fernando Chico Ponce de León",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/54-1.webp",
        width: 500,
        height: 600,
        caption: "Suit sinfónica Hospital Infantil de México Gloria Tapia",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/26.webp",
        width: 280,
        height: 500,
        caption: "Doctus - Maridel Macluff",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/39-2.webp",
        width: 1100,
        height: 200,
        caption: "Boceto 1 - Francisco Eppens",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/49.webp",
        width: 1000,
        height: 600,
        caption: "Constelaciones - Santiago Soto Urrutia",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/10.webp",
        width: 110,
        height: 150,
        caption: "Sin título 1 Alejandro Reyna, “M.Aless”",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/54-2.webp",
        width: 520,
        height: 600,
        caption: "Suit sinfónica Hospital Infantil de México Gloria Tapia",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/48.webp",
        width: 1060,
        height: 600,
        caption: "Cardumen - Santiago Soto Urrutia",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/57.webp",
        width: 850,
        height: 250,
        caption: "Niños de México Anónimo",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/15.webp",
        width:550,
        height: 400,
        caption: "Medicina lunar - Antonio Suárez",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/23.webp",
        width: 130,
        height: 200,
        caption: "Dr. Maximiliano Ruíz Castañeda - Jorge Alarcón",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/40.webp",
        width: 1090,
        height: 600,
        caption: "Croquis para el hosopital infantil Juan O Gorman",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/42.webp",
        width: 550,
        height: 900,
        caption: "Obras perdidas Francisco Eppens",
      },
      {
        src: "https://himfg.edu.mx/archivos/graficos/legado-artistico/47.webp",
        width: 1090,
        height: 600,
        caption: "Enjambre  - Santiago Soto Urrutia",
      },
]