export const data = {
  MerchantID: "8878254",
  User: "a8878254",
  Password: "C0M51him$%",
  Mode: "AUT",
  ControlNumber: "HIM001",
  TerminalID: "8878254",
  Amount: "1.00",
  MerchantName: "HIMFG CURSOS",
  MerchantCity: "CDMX",
  Language: "ES",
  // Merchant Cyb Params
  FirstName:'Ricardo Jose',
  LastName: 'Guevara Guzman',
  Street: 'Cerro Arenal',
  StreetNumberInt: '27 B',
  StreetNumberExt: '',
  Col: 'DR Jorge Jimenez Cantu',
  Del: 'Tlalnepantla de Baz',
  City: 'Mexico',
  State: 'Mexico',
  Country:'Mexico',
  PhoneNumber: 5531241831,
  PostalCode: '54190',
  Email: 'ricardo_ggzicm@outlook.com',
  CustomerID: '',
  CustomerPassword: '',
  DateOfBirth: '',
  Hostname: '',
  BrowserEmail: '',
  IpAddress: '',
  Comments: '',

  /* Merchant Ship Params
  ShipFirstName: '',
  ShipToLastName: '',
  ShipStreetNumberInt: '',
  ShipStreetNumberExt: '',
  ShipCol: '',
  ShipDel: '',
  ShipCity: '',
  ShipState: '',
  ShipCountry: '',
  ShipPostalCode: '',
  ShipPhoneNumber: '',
  ShipShippingMethod: '',

  // MerchantDataFields Params
  CustomDataField1: '',
  CustomDataField2: '',
  CustomDataField3: '',
  CustomDataField4: '',
  CustomDataField5: '',
  CustomDataField8: '',

  // NUEVOS CAMPOS *******************************
  CustomDataField6: '',
  CustomDataField7: '',
  CustomDataField9: '',
  CustomDataField10: '',
  CustomDataField11: '',
  CustomDataField12: '',
  CustomDataField13: '',
  CustomDataField14: '',
  CustomDataField15: '',
  CustomDataField16: '',
  CustomDataField17: '',
  CustomDataField18: '',
  CustomDataField19: '',
  CustomDataField20: '',
  CustomDataField21: '',
  CustomDataField22: '',
  CustomDataField23: '',
  CustomDataField24: '',
  CustomDataField25: '',
  CustomDataField26: '',
  CustomDataField27: '',
  CustomDataField28: '',
  CustomDataField29: '',
  CustomDataField30: '',
  CustomDataField31: '',
  CustomDataField32: '',
  CustomDataField33: '',
  CustomDataField34: '',
  CustomDataField35: '',
  CustomDataField36: '',
  CustomDataField37: '',
  CustomDataField38: '',
  CustomDataField39: '',
  CustomDataField40: '',
  CustomDataField41: '',
  CustomDataField42: '',
  CustomDataField43: '',
  CustomDataField44: '',
  CustomDataField45: '',
  CustomDataField46: '',
  CustomDataField47: '',
  CustomDataField48: '',
  CustomDataField49: '',
  CustomDataField50: '',
  CustomDataField51: '',
  CustomDataField52: '',
  CustomDataField53: '',
  CustomDataField54: '',
  CustomDataField55: '',
  CustomDataField56: '',
  CustomDataField57: '',
  CustomDataField58: '',
  CustomDataField59: '',
  CustomDataField60: '',
  CustomDataField61: '',
  CustomDataField62: '',
  CustomDataField63: '',
  CustomDataField64: '',
  CustomDataField65: '',
  CustomDataField66: '',
  CustomDataField67: '',
  CustomDataField68: '',
  CustomDataField69: '',
  CustomDataField70: '',
  CustomDataField71: '',
  CustomDataField72: '',
  CustomDataField73: '',
  CustomDataField74: '',
  CustomDataField75: '',
  CustomDataField76: '',
  CustomDataField77: '',
  CustomDataField78: '',
  CustomDataField79: '',
  CustomDataField80: '',
  CustomDataField81: '',
  CustomDataField82: '',
  CustomDataField83: '',
  CustomDataField84: '',
  CustomDataField85: '',
  CustomDataField86: '',
  CustomDataField87: '',
  CustomDataField88: '',
  CustomDataField89: '',
  CustomDataField90: '',
  CustomDataField91: '',
  CustomDataField92: '',
  CustomDataField93: '',
  CustomDataField94: '',
  CustomDataField95: '',
  CustomDataField96: '',
  CustomDataField97: '',
  CustomDataField98: '',
  CustomDataField99: '',
  CustomDataField100:'',*/
};
