export const data = {
  MerchantID: "8878254",
  User: "prueba8878254",
  Password: "C0M52him$%",
  Mode: "AUT",
  ControlNumber: "HIM001",
  TerminalID: "88782541",
  Amount: "1.00",
  CustomerRef1: "",
  CustomerRef2: "",
  CustomerRef3: "",
  CustomerRef4: "",
  CustomerRef5: "",
  MerchantName: "HIMFG CURSOS",
  MerchantCity: "CIUDAD DE MEXICO CDMX",
  Language: "ES",
  // Merchant Cyb Params
  /*FirstName:'Ricardo Jose',
  LastName: 'Guevara Guzman',
  Street: 'Cerro Arenal',
  StreetNumberInt: '27 B',
  StreetNumberExt: '',
  Col: 'DR Jorge Jimenez Cantu',
  Del: 'Tlalnepantla de Baz',
  City: 'Mexico',
  State: 'Mexico',
  Country:'Mexico',
  PhoneNumber: 5531241831,
  PostalCode: '54190',
  Email: 'ricardo_ggzicm@outlook.com',
  CustomerID: '',
  CustomerPassword: '',
  DateOfBirth: '',
  Hostname: '',
  BrowserEmail: '',
  IpAddress: '',
  Comments: '',

  Merchant Ship Params
  ShipFirstName: '',
  ShipToLastName: '',
  ShipStreetNumberInt: '',
  ShipStreetNumberExt: '',
  ShipCol: '',
  ShipDel: '',
  ShipCity: '',
  ShipState: '',
  ShipCountry: '',
  ShipPostalCode: '',
  ShipPhoneNumber: '',
  ShipShippingMethod: '',

  // MerchantDataFields Params
  CustomDataField1: '',
  CustomDataField2: '',
  CustomDataField3: '',
  CustomDataField4: '',
  CustomDataField5: '',
  CustomDataField8: '',

  // NUEVOS CAMPOS *******************************
  CustomDataField6: '',
  CustomDataField7: '',
  CustomDataField9: '',
  CustomDataField10: '',
  CustomDataField11: '',
  CustomDataField12: '',
  CustomDataField13: '',
  CustomDataField14: '',
  CustomDataField15: '',
  CustomDataField16: '',
  CustomDataField17: '',
  CustomDataField18: '',
  CustomDataField19: '',
  CustomDataField20: '',
  CustomDataField21: '',
  CustomDataField22: '',
  CustomDataField23: '',
  CustomDataField24: '',
  CustomDataField25: '',
  CustomDataField26: '',
  CustomDataField27: '',
  CustomDataField28: '',
  CustomDataField29: '',
  CustomDataField30: '',
  CustomDataField31: '',
  CustomDataField32: '',
  CustomDataField33: '',
  CustomDataField34: '',
  CustomDataField35: '',
  CustomDataField36: '',
  CustomDataField37: '',
  CustomDataField38: '',
  CustomDataField39: '',
  CustomDataField40: '',
  CustomDataField41: '',
  CustomDataField42: '',
  CustomDataField43: '',
  CustomDataField44: '',
  CustomDataField45: '',
  CustomDataField46: '',
  CustomDataField47: '',
  CustomDataField48: '',
  CustomDataField49: '',
  CustomDataField50: '',
  CustomDataField51: '',
  CustomDataField52: '',
  CustomDataField53: '',
  CustomDataField54: '',
  CustomDataField55: '',
  CustomDataField56: '',
  CustomDataField57: '',
  CustomDataField58: '',
  CustomDataField59: '',
  CustomDataField60: '',
  CustomDataField61: '',
  CustomDataField62: '',
  CustomDataField63: '',
  CustomDataField64: '',
  CustomDataField65: '',
  CustomDataField66: '',
  CustomDataField67: '',
  CustomDataField68: '',
  CustomDataField69: '',
  CustomDataField70: '',
  CustomDataField71: '',
  CustomDataField72: '',
  CustomDataField73: '',
  CustomDataField74: '',
  CustomDataField75: '',
  CustomDataField76: '',
  CustomDataField77: '',
  CustomDataField78: '',
  CustomDataField79: '',
  CustomDataField80: '',
  CustomDataField81: '',
  CustomDataField82: '',
  CustomDataField83: '',
  CustomDataField84: '',
  CustomDataField85: '',
  CustomDataField86: '',
  CustomDataField87: '',
  CustomDataField88: '',
  CustomDataField89: '',
  CustomDataField90: '',
  CustomDataField91: '',
  CustomDataField92: '',
  CustomDataField93: '',
  CustomDataField94: '',
  CustomDataField95: '',
  CustomDataField96: '',
  CustomDataField97: '',
  CustomDataField98: '',
  CustomDataField99: '',
  CustomDataField100:'',*/
};

export const cerKey = 'MIIGfDCCBWSgAwIBAgITFwAA98jsynTd5WTkagABAAD3yDANBgkqhkiG9w0BAQsF ADB5MQswCQYDVQQGEwJNWDEZMBcGCgmSJomT8ixkARkWCWdmYmFub3J0ZTEeMBwG A1UEChMVU2VndXJpZGFkIGluZm9ybWF0aWNhMS8wLQYDVQQDEyZHcnVwbyBGaW5h bmNpZXJvIEJhbm9ydGUgQ0EgRW50ZXJwcmlzZTAeFw0yMzAzMDcxODMzMjRaFw0y NDAzMDYxODMzMjRaMIGoMQswCQYDVQQGEwJNWDELMAkGA1UECBMCREYxDzANBgNV BAcTBk1leGljbzErMCkGA1UEChMiR3J1cG8gRmluYW5jaWVybyBCYW5vcnRlIFNB QiBkZSBDVjEkMCIGA1UECxMbU2VndXJpZGFkIGRlIGxhIEluZm9ybWFjaW9uMSgw JgYDVQQDEx9tdWx0aWNvYnJvc2tleS51bml4LmJhbm9ydGUuY29tMIIBIjANBgkq hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0s7GPPN8TCWa0E+CxaGUsjAcrydnRweN XuVvgppANVwuwvIaCquDp2rLsZDoxbMxmFxFBFn0zaCijzO4hMSLMXP00WGwPMrx gOjai595x852DOiXV2FG3qUiAopNp/05syUI4U6+jRdzT6iOanftjC+2ruvl0L0x 9R0GkpAh9uV0yVZDURr6ESz3RCiFcCqoIc4XJpDVR6t1BtkQ52hIO4yIsDm/hmCd NWPUUrg+sexecbilS49v3EH6ATxoy7CrKvMKs+nQNc6UKkW/G8H7A1ab0r/qGqUN Lq3mmlboX3wnep1no4KgceCzAsubg5QmVCNh5RNB/1rV0UbGMnDz/QIDAQABo4IC yzCCAscwOgYDVR0RBDMwMYIfbXVsdGljb2Jyb3NrZXkudW5peC5iYW5vcnRlLmNv bYIObXVsdGljb2Jyb3NrZXkwHQYDVR0OBBYEFGf3FTZF25abvslMGAkeaf+ErFLm MB8GA1UdIwQYMBaAFNAE9s+vn2u5fdteIDRgrTMHpQzTMIHtBgNVHR8EgeUwgeIw gd+ggdyggdmGgdZsZGFwOi8vL0NOPUdydXBvJTIwRmluYW5jaWVybyUyMEJhbm9y dGUlMjBDQSUyMEVudGVycHJpc2UsQ049Q0EtQkFOT1JURS1SQSxDTj1DRFAsQ049 UHVibGljJTIwS2V5JTIwU2VydmljZXMsQ049U2VydmljZXMsQ049Q29uZmlndXJh dGlvbixEQz1nZmJhbm9ydGU/Y2VydGlmaWNhdGVSZXZvY2F0aW9uTGlzdD9iYXNl P29iamVjdENsYXNzPWNSTERpc3RyaWJ1dGlvblBvaW50MIHbBggrBgEFBQcBAQSB zjCByzCByAYIKwYBBQUHMAKGgbtsZGFwOi8vL0NOPUdydXBvJTIwRmluYW5jaWVy byUyMEJhbm9ydGUlMjBDQSUyMEVudGVycHJpc2UsQ049QUlBLENOPVB1YmxpYyUy MEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9 Z2ZiYW5vcnRlP2NBQ2VydGlmaWNhdGU/YmFzZT9vYmplY3RDbGFzcz1jZXJ0aWZp Y2F0aW9uQXV0aG9yaXR5MAsGA1UdDwQEAwIFoDA8BgkrBgEEAYI3FQcELzAtBiUr BgEEAYI3FQiD6/kGgrWPR42RE4KnnwaC4d10IoLGmF+C2P0PAgFkAgEPMBMGA1Ud JQQMMAoGCCsGAQUFBwMBMBsGCSsGAQQBgjcVCgQOMAwwCgYIKwYBBQUHAwEwDQYJ KoZIhvcNAQELBQADggEBAFlZKmsn4bLc88rZzmTLRsSV5zCNCvBgsIY7zPXkDK/a YAblxx3tuaVJBGGy5Y5w1N4tPllGUtAbOlIvs1IsLyPFjPcxl9GuBVBUp8HQIsn7 +kFUE9zV4RGNWV4a1bMjwHenPRWSripfeW/SlY0xxAqA9SsTnKp7a1REI+wSqOfA teIpPPJ/SgZW2qfByutK1ANLhazUGzlrunzvXe144IeFX3DPpab9r5LompdUyi79 OVWe3wAzaMyK5TgyY4SmPmWnKBkfXGr4r4tpH4OfYQCKCHkHH2W6foD/0O52suD9 t12TpOK+yYT5mskNOyyTg2dPYz8ctXT5Mvg/mIHFfQw='
