function cypherData(p, key) {
  var paramsE = {};
  if (paramsE !== undefined)
    $.extend(paramsE, {
      // Merchant Params
      merchantId: p.MerchantID,
      name: p.User,
      password: p.Password,
      mode: p.Mode,
      controlNumber: p.ControlNumber,
      terminalId: p.TerminalID,
      amount: p.Amount,
      merchantName: p.MerchantName,
      merchantCity: p.MerchantCity,
      lang: p.Language,
      customerRef1: p.CustomerRef1,
      customerRef2: p.CustomerRef2,
      customerRef3: p.CustomerRef3,
      customerRef4: p.CustomerRef4,
      customerRef5: p.CustomerRef5,
      /*emailCdmx: p.EmailCdmx,
      phoneCdmx: p.PhoneCdmx,
      conceptoCdmx: p.ConceptoCdmx,

      // Merchant Cyb Params
      billToFirstName: p.FirstName,
      billToLastName: p.LastName,
      billToStreet: p.Street,
      billToStreetNumber: p.StreetNumberInt,
      billToStreetNumbe2: p.StreetNumberExt,
      billToStreet2Col: p.Col,
      billToStreet2Del: p.Del,
      billToCity: p.City,
      billToState: p.State,
      billToCountry: p.Country,
      billToPhoneNumber: p.PhoneNumber,
      billToPostalCode: p.PostalCode,
      billToEmail: p.Email,
      billToCustomerId: p.CustomerID,
      billToCustomerPassword: p.CustomerPassword,
      billToDateOfBirth: p.DateOfBirth,
      billToHostname: p.Hostname,
      billToHttpBrowserEmail: p.BrowserEmail,
      billToIpAddress: p.IpAddress,
      comments: p.Comments,

      // Merchant Ship Params
      shipToFirstName: p.ShipFirstName,
      shipToLastName: p.ShipToLastName,
      shipToStreetNumber: p.ShipStreetNumberInt,
      shipToStreetNumber2: p.ShipStreetNumberExt,
      shipToStreet2Col: p.ShipCol,
      shipToStreet2Del: p.ShipDel,
      shipToCity: p.ShipCity,
      shipToState: p.ShipState,
      shipToCountry: p.ShipCountry,
      shipToPostalCode: p.ShipPostalCode,
      shipToPhoneNumber: p.ShipPhoneNumber,
      shipToShippingMethod: p.ShipShippingMethod,

      // MerchantDataFields Params
      merchantDefinedDataField1: p.CustomDataField1,
      merchantDefinedDataField2: p.CustomDataField2,
      merchantDefinedDataField3: p.CustomDataField3,
      merchantDefinedDataField4: p.CustomDataField4,
      merchantDefinedDataField5: p.CustomDataField5,
      merchantDefinedDataField8: p.CustomDataField8,
      merchantDefinedDataField6: p.CustomDataField6,
      merchantDefinedDataField7: p.CustomDataField7,
      merchantDefinedDataField9: p.CustomDataField9,
      merchantDefinedDataField10: p.CustomDataField10,
      merchantDefinedDataField11: p.CustomDataField11,
      merchantDefinedDataField12: p.CustomDataField12,
      merchantDefinedDataField13: p.CustomDataField13,
      merchantDefinedDataField14: p.CustomDataField14,
      merchantDefinedDataField15: p.CustomDataField15,
      merchantDefinedDataField16: p.CustomDataField16,
      merchantDefinedDataField17: p.CustomDataField17,
      merchantDefinedDataField18: p.CustomDataField18,
      merchantDefinedDataField19: p.CustomDataField19,
      merchantDefinedDataField20: p.CustomDataField20,
      merchantDefinedDataField21: p.CustomDataField21,
      merchantDefinedDataField22: p.CustomDataField22,
      merchantDefinedDataField23: p.CustomDataField23,
      merchantDefinedDataField24: p.CustomDataField24,
      merchantDefinedDataField25: p.CustomDataField25,
      merchantDefinedDataField26: p.CustomDataField26,
      merchantDefinedDataField27: p.CustomDataField27,
      merchantDefinedDataField28: p.CustomDataField28,
      merchantDefinedDataField29: p.CustomDataField29,
      merchantDefinedDataField30: p.CustomDataField30,
      merchantDefinedDataField31: p.CustomDataField31,
      merchantDefinedDataField32: p.CustomDataField32,
      merchantDefinedDataField33: p.CustomDataField33,
      merchantDefinedDataField34: p.CustomDataField34,
      merchantDefinedDataField35: p.CustomDataField35,
      merchantDefinedDataField36: p.CustomDataField36,
      merchantDefinedDataField37: p.CustomDataField37,
      merchantDefinedDataField38: p.CustomDataField38,
      merchantDefinedDataField39: p.CustomDataField39,
      merchantDefinedDataField40: p.CustomDataField40,
      merchantDefinedDataField41: p.CustomDataField41,
      merchantDefinedDataField42: p.CustomDataField42,
      merchantDefinedDataField43: p.CustomDataField43,
      merchantDefinedDataField44: p.CustomDataField44,
      merchantDefinedDataField45: p.CustomDataField45,
      merchantDefinedDataField46: p.CustomDataField46,
      merchantDefinedDataField47: p.CustomDataField47,
      merchantDefinedDataField48: p.CustomDataField48,
      merchantDefinedDataField49: p.CustomDataField49,
      merchantDefinedDataField50: p.CustomDataField50,
      merchantDefinedDataField51: p.CustomDataField51,
      merchantDefinedDataField52: p.CustomDataField52,
      merchantDefinedDataField53: p.CustomDataField53,
      merchantDefinedDataField54: p.CustomDataField54,
      merchantDefinedDataField55: p.CustomDataField55,
      merchantDefinedDataField56: p.CustomDataField56,
      merchantDefinedDataField57: p.CustomDataField57,
      merchantDefinedDataField58: p.CustomDataField58,
      merchantDefinedDataField59: p.CustomDataField59,
      merchantDefinedDataField60: p.CustomDataField60,
      merchantDefinedDataField61: p.CustomDataField61,
      merchantDefinedDataField62: p.CustomDataField62,
      merchantDefinedDataField63: p.CustomDataField63,
      merchantDefinedDataField64: p.CustomDataField64,
      merchantDefinedDataField65: p.CustomDataField65,
      merchantDefinedDataField66: p.CustomDataField66,
      merchantDefinedDataField67: p.CustomDataField67,
      merchantDefinedDataField68: p.CustomDataField68,
      merchantDefinedDataField69: p.CustomDataField69,
      merchantDefinedDataField70: p.CustomDataField70,
      merchantDefinedDataField71: p.CustomDataField71,
      merchantDefinedDataField72: p.CustomDataField72,
      merchantDefinedDataField73: p.CustomDataField73,
      merchantDefinedDataField74: p.CustomDataField74,
      merchantDefinedDataField75: p.CustomDataField75,
      merchantDefinedDataField76: p.CustomDataField76,
      merchantDefinedDataField77: p.CustomDataField77,
      merchantDefinedDataField78: p.CustomDataField78,
      merchantDefinedDataField79: p.CustomDataField79,
      merchantDefinedDataField80: p.CustomDataField80,
      merchantDefinedDataField81: p.CustomDataField81,
      merchantDefinedDataField82: p.CustomDataField82,
      merchantDefinedDataField83: p.CustomDataField83,
      merchantDefinedDataField84: p.CustomDataField84,
      merchantDefinedDataField85: p.CustomDataField85,
      merchantDefinedDataField86: p.CustomDataField86,
      merchantDefinedDataField87: p.CustomDataField87,
      merchantDefinedDataField88: p.CustomDataField88,
      merchantDefinedDataField89: p.CustomDataField89,
      merchantDefinedDataField90: p.CustomDataField90,
      merchantDefinedDataField91: p.CustomDataField91,
      merchantDefinedDataField92: p.CustomDataField92,
      merchantDefinedDataField93: p.CustomDataField93,
      merchantDefinedDataField94: p.CustomDataField94,
      merchantDefinedDataField95: p.CustomDataField95,
      merchantDefinedDataField96: p.CustomDataField96,
      merchantDefinedDataField97: p.CustomDataField97,
      merchantDefinedDataField98: p.CustomDataField98,
      merchantDefinedDataField99: p.CustomDataField99,
      merchantDefinedDataField100: p.CustomDataField100,*/
    });
  let ret = "";

  jQuery.ajax({
    //url: "https://localhost:7080/aes/cifradoconllave", // Desde Visual Studio 2022
    //url : 'http://localhost:5080/aes/cifradoconllave',  // Desde Ejecutable Cifrador.exe
    url: "http://ricardoggz-001-site1.itempurl.com/aes/cifradoconllave",
    type: "POST",
    async: false,
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Headers": "Content-Type",
      "Access-Control-Allow-Methods": "OPTIONS,POST,GET",
    },
    data: JSON.stringify({
      base64: window.btoa(JSON.stringify(paramsE)),
      pubKeyStrCert: key,
    }),
    contentType: "application/json; charset=utf-8",
    dataType: "json",
    success: function (response) {
      ret = response;
    },
  });
  return ret["data"]["0"];
}
export { cypherData };
