import Head from 'next/head'
import { RegisterForm, Container, Title } from '../../components'

const Register = ()=>{
    return (
        <>
            <Head>
                <title>Inscripción en línea</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="https://res.cloudinary.com/diuxbqmn5/image/upload/v1677114497/himfg-logo_ewzx59.webp" />
            </Head>
            <Container>
                <Title>Inscripción en línea</Title>
                <RegisterForm />
            </Container>
        </>
    )
}
export default Register